# Note: all environments run nodejs, so set language to PHP so we can lint all of the PHP functions
language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - master

install:
  - npm install
  - make

script:
  - make test_changes
  - make test_eslint
  - make test_node
  - make test_php

branches:
  only:
    - master
    - travis

matrix:
  include:
    - language: nix
      install:
      script: nix-build --argstr handlebarsSpecVersion $TRAVIS_BRANCH
